const IMG = '/Images';

// Single source of truth for the product catalog (used by scripts/seed.mjs).
export const defaultProducts = [
  { name: 'HELL CLASSIC', category: 'Energy Drink', caffeine: '32 mg/100 ml', price: 120, stock: 100, vitamins: ['B2 (Riboflavin)', 'B3 (Niacin)', 'B5 (Pantothenic Acid)', 'B6', 'B12'], description: 'Inimitable, classic flavour, the flagship, the first HELL! It always enchants with its original tutti-frutti taste, proving that classic drinks are the best — in an easily recognizable red and black style.', imageUrl: `${IMG}/HELL_NEW_GEN_CLASSIC_250_01_HU.png.png`, isFeatured: true },
  { name: 'HELL BLACK CHERRY', category: 'Energy Drink', caffeine: '32 mg/100 ml', price: 120, stock: 100, vitamins: ['B2', 'B3', 'B5', 'B6', 'B12'], description: 'Special black cherry taste in stylish purple-black packaging. This tempting, refreshing tutti-frutti-based energy drink captures the essence of a sunny day in a single sip.', imageUrl: `${IMG}/HELL_Black_Cherry_250_ED_01-1.png.png`, isFeatured: false },
  { name: 'HELL STRONG APPLE', category: 'Energy Drink', caffeine: '38.4 mg/100 ml (+20%)', price: 140, stock: 100, vitamins: ['B2', 'B3', 'B5', 'B6', 'B12'], description: 'One of our most popular energy drinks, with the exciting combination of apple and tutti-frutti flavour. +20% more caffeine than our classic products — the perfect partner for an active lifestyle.', imageUrl: `${IMG}/HELL_Strong_Apple_250_ED-cutout-cutout.png.png`, isFeatured: true },
  { name: 'HELL STRONG WATERMELON', category: 'Energy Drink', caffeine: '38.4 mg/100 ml (+20%)', price: 140, stock: 100, vitamins: ['B2', 'B3', 'B5', 'B6', 'B12'], description: 'Juicy watermelon flavour with +20% more caffeine and five different B-vitamins, completely preservative-free in a fully recyclable package.', imageUrl: `${IMG}/HELL_Strong_Watermelon_250_ED_01.png.png`, isFeatured: false },
  { name: 'HELL STRONG RED GRAPE', category: 'Energy Drink', caffeine: '38.4 mg/100 ml (+20%)', price: 140, stock: 100, vitamins: ['B2', 'B3', 'B5', 'B6', 'B12'], description: 'Deep, sweet red grape character paired with a powerful +20% caffeine boost. Bold taste, bold energy, bold design.', imageUrl: `${IMG}/HELL_Strong_RedGrape_250_ED-copy.png.png`, isFeatured: false },
  { name: 'HELL GREEN APPLE', category: 'Energy Drink', caffeine: '32 mg/100 ml', price: 120, stock: 100, vitamins: ['B2', 'B3', 'B5', 'B6', 'B12'], description: 'Crisp, fresh green apple flavour with the signature HELL energy formula — 5 B-vitamins, no preservatives, infinitely recyclable can.', imageUrl: `${IMG}/HELL_GREEN_APPLE_HU_PACKSHOTs_fentrol.png.png`, isFeatured: false },
  { name: 'HELL PINK GUAVA', category: 'Energy Drink', caffeine: '32 mg/100 ml', price: 130, stock: 100, vitamins: ['B2', 'B3', 'B5', 'B6', 'B12'], description: 'Exotic pink guava in the bold New Generation design. A tropical, refreshing twist on the energy you know and love.', imageUrl: `${IMG}/HELL_NEW_GEN_PINK_GUAVA_250_01_HU.png.png`, isFeatured: true },
  { name: 'HELL NIGHT', category: 'Energy Drink', caffeine: '32 mg/100 ml', price: 130, stock: 100, vitamins: ['B2', 'B3', 'B5', 'B6', 'B12'], description: 'A dark, mysterious flavour profile built for the night. Sleek black styling and full HELL energy to power your late hours.', imageUrl: `${IMG}/HELL_Night_250_ED_01.png.png`, isFeatured: false },
  { name: 'HELL CAFFEINE FREE', category: 'Energy Drink', caffeine: '0 mg/100 ml', price: 120, stock: 100, vitamins: ['B2', 'B3', 'B5', 'B6', 'B12'], description: 'All the iconic HELL taste and B-vitamins, with zero caffeine. Enjoy the flavour any time of day, on your terms.', imageUrl: `${IMG}/HELL_CAFFEINE_FREE_250_ED_01.png.png`, isFeatured: false },
  { name: 'HELL ZERO CLASSIC', category: 'Energy Drink', caffeine: '32 mg/100 ml', price: 120, stock: 100, vitamins: ['B2', 'B3', 'B5', 'B6', 'B12'], description: 'The favourite tutti-frutti taste with zero sugar. Made with 5 B-vitamins, 0 preservatives and 0 sugar — no compromise.', imageUrl: `${IMG}/HELL_Zero_CLASSIC_2025_HU_PACKSHOTs_2.png.png`, isFeatured: false },
  { name: 'HELL ZERO BERRY', category: 'Energy Drink', caffeine: '32 mg/100 ml', price: 120, stock: 100, vitamins: ['B2', 'B3', 'B5', 'B6', 'B12'], description: 'Vibrant mixed-berry flavour with zero sugar. Refreshing, light and fully loaded with the HELL vitamin complex.', imageUrl: `${IMG}/HELL_Zero_BERRY_2025_HU_PACKSHOTs_2.png.png`, isFeatured: false },
  { name: 'HELL ZERO WHITE PEACH', category: 'Energy Drink', caffeine: '32 mg/100 ml', price: 130, stock: 100, vitamins: ['B2', 'B3', 'B5', 'B6', 'B12'], description: 'Delicate white peach flavour, zero sugar. A smooth, summery experience with the full energy kick.', imageUrl: `${IMG}/HELL_Zero_WHITE_PEACH_2025_HU_PACKSHOTs_2.png.png`, isFeatured: true },
  { name: 'HELL FOCUS+', category: 'Functional Drink', caffeine: '38.4 mg/100 ml (+20%)', price: 150, stock: 100, vitamins: ['C', 'D', 'B2', 'B3', 'B6', 'B12'], description: 'A functional line created to support mental concentration. +20% caffeine, added Vitamin C and D plus B-vitamins, in a modern, hyper-energetic design.', imageUrl: `${IMG}/HELL_Focus_250_ED_01.png.png`, isFeatured: true },
  { name: 'HELL MULTI+', category: 'Functional Drink', caffeine: '32 mg/100 ml', price: 150, stock: 100, vitamins: ['A', 'C', 'E', 'B2', 'B3', 'B6', 'B12'], description: 'Recharge with MULTI+ — additional vitamins, renewed packaging and a new recipe. Supports the normal functioning of the immune system with vitamins A, C and E.', imageUrl: `${IMG}/HELL_Multi_250_ED_01.png.png`, isFeatured: false },
  { name: 'HELL CARNIVAL CACTUS TWIST', category: 'Energy Drink', caffeine: '32 mg/100 ml', price: 150, stock: 100, vitamins: ['B2', 'B3', 'B5', 'B6', 'B12'], description: 'Limited Carnival Edition! A playful blend of strawberry and lemon — fresh, nostalgic and adventurous. Tastes like a festival in a can.', imageUrl: `${IMG}/HELL_Carnival_ED_Cactus_Twist_2026_HU_Packshot_01.png.png`, isFeatured: true },
  { name: 'HELL CARNIVAL COTTON CANDY', category: 'Energy Drink', caffeine: '32 mg/100 ml', price: 150, stock: 100, vitamins: ['B2', 'B3', 'B5', 'B6', 'B12'], description: 'Limited Carnival Edition! Sweet, nostalgic cotton candy flavour — a trip back to childhood with a full HELL energy boost.', imageUrl: `${IMG}/HELL_Carnival_ED_Cotton_Candy_2026_HU_Packshot_01.png.png`, isFeatured: true },
];
